# Generated by Django 3.2.4 on 2022-09-12 19:22

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0017_auto_20220912_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='nameClient',
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
